import cv2
import base64
import hashlib
import numpy as np
from cryptography.fernet import Fernet


class Encoder:
    """
    The class responsible for the encoding of a binary string within an image
    """

    def __init__(self, filename_, text_, offset_, custom_key_):  # Initialising class attributes
        """
        Initialising the encoder class with filename, text, offset and custom key (optional)


        filename_ (str): The filename of the image
        text_ (str): The text to encode
        offset_ (int)(optional): The number of bytes the text will be offset by
        custom_key_ (str)(optional): The custom key that will be used to encrypt the text
        """
        self.text_ = text_
        self.message_ = ""
        self.binary_text_ = ""
        self.offset_ = int(offset_)
        self.key_ = Fernet.generate_key()

        self.custom_key_ = custom_key_

        self.filename_ = filename_
        self.img = cv2.imread(self.filename_)  # Loading the image into self.img
        self.binary_img_ = (np.vectorize(np.binary_repr, otypes=[str])(self.img, width=8))  # Converting img to binary
        self.array_shape_ = np.shape(self.binary_img_)

        self.start_byte = "1010101010101010"
        self.stop_byte = "1111111010111110"

    def key_gen(self):
        """
        Responsible for generating a key that will be used in the encryption process

        if a custom key has been set then that custom key then gets processed into a key use-able by fernet
        returns self.custom_key_ (bytes): Returns the processed custom key

        if a custom key has not been set then one is generated
        returns self.key_ (fernet): Returns newly generated key
        """
        if self.custom_key_ is not None:
            hlib = hashlib.md5()
            hlib.update(str(self.custom_key_).encode())

            self.custom_key_ = base64.urlsafe_b64encode(hlib.hexdigest().encode())
            return self.custom_key_

        else:
            self.key_ = Fernet.generate_key()
            print(self.key_.decode())
            return self.key_

    def message_generator(self):
        """
        Responsible for the encryption of the message as well as converting it to a binary string
        the start byte, binary string and stop byte are added together to create the message to encode

        returns self.message_ (str): Returns a formatted binary string
        """
        f = Fernet(self.key_gen())
        encrypted = f.encrypt(self.text_.encode())

        self.binary_text_ = ' '.join(format(ord(x), '08b') for x in encrypted.decode())  # Converting text into binary
        self.binary_text_ = self.binary_text_.replace(" ", "")  # Removing spaces from the binary text
        self.message_ = self.start_byte + self.binary_text_ + self.stop_byte  # Creating message sequence

        return self.message_

    def set_byte(self):
        """
        Replaces each byte in the image with a new byte generated by taking the original byte and replaceing
        the least significant bit with each bit from the binary string

        Nothing is returned, the newly modified image is saved to a file
        """
        self.message_ = self.message_generator()

        total_space = (self.array_shape_[0] * self.array_shape_[1] * self.array_shape_[2])
        if (len(self.message_) + self.offset_) > total_space:  # Check to see if text can fit in image
            print("Error: Not enough space. Chose a smaller offset or a smaller message")
            quit()

        byte_counter = 0
        counter = 0
        for y in range(self.array_shape_[0]):  # Incrementing for Y axis of pixels
            for x in range(self.array_shape_[1]):  # Incrementing for X axis of pixels
                for byte in range(self.array_shape_[2]):  # Incrementing for each byte within an RGB series
                    if byte_counter == self.offset_:
                        current_byte = self.binary_img_[y, x, byte]  # Storing the current byte

                        new_byte = current_byte[:-1]  # Removing the least significant bit from the byte

                        new_byte += self.message_[counter]  # Adding 1 bit from the message binary to the new byte

                        self.binary_img_[y][x][byte] = new_byte  # Adding the new byte to the binary image array
                        if counter == len(self.message_) - 1:
                            base_repr_vector = (
                                np.vectorize(int))  # Preparing function to convert array string to array integer

                            cv2.imwrite(self.filename_[:-4] + "_encoded.png",
                                        base_repr_vector(self.binary_img_, 2))  # Writing new image to file
                            return "Image Successfully Encoded"
                        else:
                            counter += 1
                    else:
                        new_byte = self.binary_img_[y, x, byte]
                        new_byte = new_byte[:-1]
                        self.binary_img_[y, x, byte] = (new_byte + "0")
                        byte_counter += 1
